name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  VITE_BUNGIE_API_KEY: ${{ secrets.VITE_BUNGIE_API_KEY }}
  VITE_BUNGIE_API_AUTHURL: ${{ secrets.VITE_BUNGIE_API_AUTHURL }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  VITE_BUNGIE_API_APP: ${{ secrets.VITE_BUNGIE_API_APP }}
  VITE_SENTRY_SCRIPT: ${{ secrets.VITE_SENTRY_SCRIPT }}

concurrency:
  group: "dataverse-app"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist
          cname: overlay.eververse.trade
